version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: ../
        target: /var/www
        consistency: cached
      - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - type: bind
        source: ../
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    networks:
      - www
    environment:
      XDEBUG_CONFIG: client_host=${MYIP}
      DEBUG: 1
    expose:
      - 9000
    working_dir: /var/www
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
    networks:
      - www
networks:
  www:
    driver: bridge
volumes:
  db:
    driver: local
